---
- name: Ensure postfix is installed (RedHat).
  yum: name=postfix state=installed
  when: ansible_os_family == 'RedHat'

- name: Ensure postfix is installed (Debian).
  apt: name=postfix state=installed
  when: ansible_os_family == 'Debian'

- lineinfile: dest="/etc/postfix/main.cf" line="inet_protocols = ipv4"
  when: postfix_ipv4 == 'true'

- lineinfile: dest="/etc/postfix/main.cf" line="inet_protocols = ipv4" state=absent
  when: postfix_ipv4 == 'false'

- name: Ensure postfix is started and enabled at boot.
  service: name=postfix state=started enabled=yes
