---
- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present

- name: Update Postfix configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
    mode: 0644
  with_items:
    - name: inet_interfaces
      value: "{{ postfix_inet_interfaces }}"
    - name: inet_protocols
      value: "{{ postfix_inet_protocols }}"
  when: postfix_template is not defined
  notify: restart postfix

- name: Apply Postfix template
  template:
    dest: "{{ postfix_config_file }}"
    src: "{{ postfix_template }}"
    mode: 0644
  when: postfix_template is defined
  notify: restart postfix

- name: Apply transport template if any transport rule is defined
  template:
    src: "{{ postfix_transport_template }}"
    dest: "{{ postfix_transport_file }}"
    mode: 0644
  when: postfix_transport is defined
  register: transport_file

- name: Build postmap
  command: postmap {{ postfix_transport_file }}
  when: transport_file.changed

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"
